---
- hosts: dbservers
  become: true
  vars:
    mysql_root_password: "Dp@145"
    mysql_database: "yahve"
    mysql_user: "yahve"
    mysql_password: "E1381411dm"

  tasks:
    - name: Add MariaDB repository key
      apt_key:
        url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xF1656F24C74CD1D8
        state: present
    - name: Add MariaDB repository
      apt_repository:
        repo: deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/10.10/ubuntu jammy main
        state: present
        update_cache: yes
    - name: Install MariaDB
      apt:
        name: mariadb-server
        state: present
    - name: Install Python3 pip
      apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL
      pip:
        name: pymysql
        executable: pip3
    - name: Set MariaDB root password
      mysql_user:
        name: root
        password: "{{ mysql_root_password }}"
        login_unix_socket: /var/run/mysqld/mysqld.sock

