- name: Install Nginx
  hosts: webservers
  become: true
  tasks:
    - name: Add Nginx GPG key
      apt_key:
        url: http://nginx.org/keys/nginx_signing.key
        state: present

    - name: Add Nginx APT repository
      apt_repository:
        repo: deb http://nginx.org/packages/ubuntu/ jammy nginx
        state: present

    - name: Install Nginx package
      apt:
        name: nginx
        state: latest

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Upload a new Nginx configuration
      copy:
        src: /var/www/ansible/nginx/nginx.conf
        dest: /etc/nginx/conf.d/yahve.conf
        owner: root
        group: root
        mode: 0644

    - name: Ensure Nginx is running
      systemd:
        name: nginx
        state: started
        enabled: yes
